### ISSUE TITLE
Add Affix support to node state transition scripts

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/clearinghouse#123]
The backend's node transition scripts need to be adapted to successfully contact (and then set up) nodes that are using Affixes, e.g ones behind NATs. Use the ```seash```-related changeset r7084 as a blueprint on how to enable Affixes.

**Comment by aaaaalbert** [comment]
Implemented in 469f78b4bf62029d9d70f1a4833b80673eff762e. Closing.
