### ISSUE TITLE
Custom Installer Builder has no Android download

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/clearinghouse#130]
The Seattle Custom Installer Builder should provide a customized Android Package (APK), too! I suppose a bit of self-signing will be required. The user will probably need to check an "Install from unknown sources" box in their device's config before they can install, as the APK doesn't come from Google Play.

AFAIR, the process of building locally has been implemented by Akos Lukovics in source:trunk/dist/make_base_installers.py before !SeattleOnAndroid went to live on Google Play. See also BuildingSeattleOnAndroid and #1115.

**Comment by aaaaalbert** [comment]
The original ticket description asserted that the CIB will ship the actual APK, which is not the case the way we implemented Android support in aaaaalbert/custominstallerbuilder. To the contrary, we have the app on Google Play (so anyone can download an altruistic / "flibble" installer from there); if desired, the CIB URL to a specifically built installer is provided to the app during install, and the installer subsequently downloaded from that URL.

I'm closing this issue as "solved in a private fork that will become the new master soon."
