### ISSUE TITLE
Creating additional dir's before hand

### ISSUE THREAD

**Issue by asm582** [SeattleTestbed/clearinghouse#154]
In the link https://seattle.poly.edu/wiki/ClearinghouseInstallation : 

1) Before running command chmod +x generate_state_keys.sh
we should create statekeys under dir /clearinghouse/node_state_transitions/statekeys

2)Before running "start_cleairnghouse_components.sh" we need to create logs dir under clearinghouse/logs.

**Comment by aaaaalbert** [comment]
See #149.
