### ISSUE TITLE
Skip mode in initialize.py / old version of initialize.py

### ISSUE THREAD

**Issue by awwad** [SeattleTestbed/clearinghouse#162]
Skip mode seems not to be functioning in this repository's [initialize.py](../tree/master/scripts/initialize.py). Seems to be older than [current version of initialize.py from buildscripts repo](https://github.com/SeattleTestbed/buildscripts/tree/master/initialize.py)

Tried python initialize.py -s, but that didn’t actually skip the stuff already in DEPENDENCIES, and it errors out if they’re already there, so in practice I had to comment out the lines in build_initialize.txt relating to the already-cloned dependencies and run initialize.py again.

The buildscripts need to not require this hassle if a clone fails.

**Comment by aaaaalbert** [comment]
Please send a pull request with the current buildscripts.

**Comment by awwad** [comment]
Done <https://github.com/SeattleTestbed/clearinghouse/pull/164>. Awkward,
github, awkward. (Git, too, for that matter - notes
<https://docs.google.com/document/d/1E3XXdIegfqF2j7K64r7OCRpkwiH2rc3eYZ0FSE5ot3U/edit#>
.)

**Comment by aaaaalbert** [comment]
Fixed in #164.
